language: csharp
solution: NLog.Extensions.Hosting.sln
mono: none
dotnet: 2.1.300

install:
  - dotnet restore NLog.Extensions.Hosting.sln
  - dotnet add test/NLog.Extensions.Hosting.Tests/NLog.Extensions.Hosting.Tests.csproj package xunit.runner.console
  # Display dotnet version info
  - which dotnet;
    if [ $? -eq 0 ]; then
      echo "Using dotnet:";
      dotnet --info;
    else
      echo "dotnet.exe not found"
      exit 1;
    fi

script:
 # Run tests
  - dotnet test test/NLog.Extensions.Hosting.Tests --configuration Debug
