version: '{build}'
image: Visual Studio 2017

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - master

nuget:
  disable_publish_on_pr: true

artifacts:
  - path: '**\*.nupkg'
    name: All generated NuGet packages

environment:
  github_auth_token:
    secure: WYvd/k1xGCsDS+4iOhjzxA5/e36RjkxnuVOHpBR+eDtZNNjpYydCyNfd1COME9jI
  sonar_token:
    secure: OUI/jCbBF75TwKMPT+IfewdgwCgx9nQkRg3cYOEQNJeX5J2++oWS3dmpwO51XduP

install:
  - ps: dotnet tool install --global dotnet-sonarscanner
  - ps: cinst opencover.portable
  - ps: cinst codecov

before_build:
  - nuget restore

build:
  parallel: true
  project: NLog.Extensions.Hosting.Sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal

after_build:
  -  ps: dotnet pack .\NLog.Extensions.Hosting.sln /p:Configuration=PreRelease

test_script:
  - ps: OpenCover.Console.exe -register:user -target:"dotnet.exe" -targetargs:"test --logger:trx;LogFileName=results.trx /p:DebugType=full test/NLog.Extensions.Hosting.Tests/NLog.Extensions.Hosting.Tests.csproj" -filter:"+[NLog.Extensions.Hosting*]* -[NLog.Extensions.Hosting.Tests*]*" -output:".\coverage.xml" -oldstyle
  - ps: .\run-sonar.ps1
  - ps: codecov -f .\coverage.xml

deploy:
  - provider: NuGet
    name: preRelease
    api_key:
      secure: DtVDH1ZfIR8E2oDLeSPxfn0WFXw3MCv4WhLkkQQl9LfEHswb5sdxdCYodNKhrKik
    artifact: /.*-rc.*\.nupkg/
  - provider: NuGet
    name: production
    api_key:
      secure: DtVDH1ZfIR8E2oDLeSPxfn0WFXw3MCv4WhLkkQQl9LfEHswb5sdxdCYodNKhrKik
    artifact: /.*NLog\.Extensions\.Hosting\.\d+\.\d+\.\d+\.nupkg/
    on:
      branch: master
      appveyor_repo_tag: true
