version: '{build}'

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - master

nuget:
  disable_publish_on_pr: true

environment:
  github_auth_token:
    secure: WYvd/k1xGCsDS+4iOhjzxA5/e36RjkxnuVOHpBR+eDtZNNjpYydCyNfd1COME9jI
  sonar_token:
    secure: OUI/jCbBF75TwKMPT+IfewdgwCgx9nQkRg3cYOEQNJeX5J2++oWS3dmpwO51XduP

build_script:
  - ps: .\build.ps1

artifacts:
  - path: .\artifacts\**\*.nupkg
  - name: NuGet

test_script:
  - dotnet tool install --global dotnet-sonarscanner
  - nuget.exe install OpenCover -ExcludeVersion -DependencyVersion Ignore
  - OpenCover\tools\OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test -f netcoreapp2.1" -filter:"+[NLog.Extensions.Hosting]* -[NLog.Extensions.Hosting.Tests]*" -output:"coverage.xml" -oldstyle -targetdir:"test/NLog.Extensions.Hosting.Tests"
  - pip install codecov
  - codecov -f "coverage.xml"
  - ps: .\run-sonar.ps1
  - ps: .\run-tests.ps1

deploy:
- provider: NuGet
  name: ci-MyGet-feed
  server: https://www.myget.org/F/sheepreaper-ci/api/v3/index.json
  api_key:
    secure: CHaiyKKxNlq9ofjee3YItXa1AYdsj1caQHBI7kubVctln1I5n7odhxEQkRxvd6mz
  skip_symbols: true
  on:
  branch: master
- provider: NuGet
  name: production-NuGet
  api_key:
    secure: DtVDH1ZfIR8E2oDLeSPxfn0WFXw3MCv4WhLkkQQl9LfEHswb5sdxdCYodNKhrKik
  artifact: /.*\.nupkg/
  on:
    branch: master
    appveyor_repo_tag: true